[build]
publish = "dist"
command = "pnpm build"

[context.deploy-preview]
command = "pnpm build"

[context.branch-deploy]
command = "pnpm build"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200
